### PR TITLE
 - Disable check for pthreads on win32

### PR DESCRIPTION
**Pull request by felfert**
Hi,

I'm building your mingw32 branch of pulseaudio on Fedora 15. On this distro, a win32 port of pthreads-2.8.0 is installed by default. (Your OBS build does not fail, because on openSUSE 11.4, this apparently is missing) buildhost) Infortunately, this libpthread does not support various signal related stuff. Since using pthreads on win32 breaks pulseaudio anyway, I wrapped the invocation of the AX_PTHREAD macro in configure.ac into a check for win32.

Please consider a pull ...

Thanks
- Fritz

### CODE REVIEW

**Comment by felfert** [comment]
Hmpf - Of course this pull should go into your mingw32 branch, not in master. Don't know how the branch got unpinned here.

**Comment by felfert** [comment]
Another fix regarding build failure if win32-pthreads are installed when building on mingw.

**Comment by mkbosmans** [comment]
Indeed, pthread is unsupported for windows, as we use the native win32 threading primitives for pulseaudio. I have never tested the mingw build with pthread-win32 installed, so some problems were expected.

From the second patch I get that with pthread-win32 installed, the sched.h header is also provided? If that's the case that patch is OK too.

As you said, the pull request is not against the mingw32 branch. But even if it were, I would have to ask on the pulseaudio mailing list to get my branch pulled. So I propose that you do a git-format-patch and send that to the mailing list directly. I'll ack it and someone with commit priviliges to the pulse git master can then commit it.

**Comment by felfert** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA1

On 16.06.2011 10:55, mkbosmans wrote:

> Indeed, pthread is unsupported for windows, as we use the native win32 threading primitives for pulseaudio. I have never tested the mingw build with pthread-win32 installed, so some problems were expected.
> 
> From the second patch I get that with pthread-win32 installed, the sched.h header is also provided? If that's the case that patch is OK too.

Exactly. sched.h is provided by that pthread package. Before somebody asks:
My first approach was to make the configure test for it conditional -
just like with AX_PTHREAD. Unfortunately, this results in many
subsequent checks failing. Therefore, I resorted to disabling the
relevant part in the code.

> As you said, the pull request is not against the mingw32 branch. But even if it were, I would have to ask on the pulseaudio mailing list to get my branch pulled. So I propose that you do a git-format-patch and send that to the mailing list directly. I'll ack it and someone with commit priviliges to the pulse git master can then commit it.
> 
> I must admit as on old-school (cvs/svn) guy, I'm a little bit lost here.
> I generated that pull request by using github's webgui. So could you
> please help me with generating that formatted patch via cmdline?

-----BEGIN PGP SIGNATURE-----
Version: GnuPG v1.4.6 (MingW32)
Comment: Using GnuPG with Mozilla - http://enigmail.mozdev.org/

iD8DBQFN+hCcboM4mAMyprARApw8AJ0RC9hZP+2yWzI9+kcq0iL1Kf6GnACePfLY
BcK7szVkDzIT9K64OKmfLpU=
=yiZ4
-----END PGP SIGNATURE-----

**Comment by mkbosmans** [comment]
I think the following will do, assuming you have git installed

# global setup

git config --global user.name "Your Name Comes Here"
git config --global user.email you@yourdomain.example.com

# Pull complete repository and switch to mingw-build branch. The clone

command may take a while as it downloads all the history from the
repository (this is the distributed part of git, compared to e.g. svn
where a checkout only has the latest commit)
git clone git://github.com/felfert/pulseaudio.git
cd pulseaudio/
git checkout mingw32-build

# Make patches from the last two commits in the current branch

git format-patch HEAD~2

The clone command is only needed once, from now on, you can sync with
github using git pull and git push.

Maarten

2011/6/16 felfert
reply@reply.github.com:

**Comment by felfert** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA1

On 06/16/2011 05:49 PM, mkbosmans wrote:

> I think the following will do, assuming you have git installed
> [...]

Ok, I figured it out - mails are sent...
-----BEGIN PGP SIGNATURE-----
Version: GnuPG v1.4.11 (GNU/Linux)
Comment: Using GnuPG with Fedora - http://enigmail.mozdev.org/

iEYEARECAAYFAk37yNsACgkQboM4mAMyprAiPwCdGPc64y51eKawFbyir1TDH9SJ
gWUAoI/6G0pVHvpqaQbqJiPL5d6kLJMb
=8slR
-----END PGP SIGNATURE-----

**Pull request closed without merging**
